num1 = int(input("Insert first number: "))
num2 = int(input("Insert second number: "))
num3 = int(input("Insert third number: "))

print("Sum: ", num1 + num2 + num3)
print("Minus: ", num1 - num2 - num3)
print("Muilty: ", num1 * num2 * num3)
print("Division: ", num1 / num2 / num3)
print("To the degree: ", num1 ** num2 ** num3)
print("Division without remainder: ", num1 % num2 % num3)